# Generated by Django 4.1.3 on 2022-11-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
