# Generated by Django 4.1.3 on 2022-11-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='thumbnail',
        ),
    ]
