# Generated by Django 4.1.3 on 2022-11-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_remove_song_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
