# Generated by Django 4.1.3 on 2022-11-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_created_album_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date_created',
        ),
    ]
