# Generated by Django 4.1.3 on 2022-11-11 09:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_song_audio_file_alter_song_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='album',
            managers=[
                ('approved_only', django.db.models.manager.Manager()),
            ],
        ),
    ]
