# Generated by Django 4.1.3 on 2022-11-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=50, unique=True)),
                ('social_media_link', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'Artists',
                'ordering': ['stage_name'],
            },
        ),
    ]
