# Generated by Django 4.1.3 on 2022-11-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_created_artist_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='modified',
        ),
    ]
